# Generated by Django 4.2.16 on 2025-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(max_length=64, unique=True)),
                ('discount_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
