# Generated by Django 4.2.16 on 2024-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
