# Generated by Django 4.2.16 on 2024-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
