# Generated by Django 4.2.16 on 2024-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_category_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="store.category"
            ),
        ),
    ]
