# Generated by Django 4.2.16 on 2024-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.category"
            ),
        ),
    ]
