# Generated by Django 4.2.16 on 2024-11-28 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_sale_alter_review_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-date_added"], "verbose_name_plural": "products"},
        ),
        migrations.AddField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
