# Generated by Django 4.2.16 on 2024-11-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_options_product_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
