# Generated by Django 4.2.16 on 2025-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
